# Gunakan image Node.js
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy semua file ke dalam container
COPY . .

# Set environment variable
ENV PORT=5000

# Expose port 5000
EXPOSE 5000

# Jalankan server
CMD ["npm", "run", "dev"]
