# Gunakan image Node.js
FROM node:18

# Set direktori kerja di dalam container
WORKDIR /app

# Copy package.json dan install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy seluruh source code ke dalam container
COPY . .

# Expose port aplikasi
EXPOSE 5000

# Perintah untuk menjalankan aplikasi
CMD ["npm", "run", "dev"]

